# site settings
remote_theme: daattali/beautiful-jekyll
title: Collaborative Source
description: building technology in a progressive way

navbar-links:
  Principles: https://collaborative-source.github.io/principles.html
  Guides: https://collaborative-source.github.io/guides.html
  Blog: https://collaborative-source.github.io/blog.html
